package ExceptionHandlingJava;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FilterInputStream;

//public class whatException {
//
//	public static void main(String[] args) {
//		// TODO Auto-generated method stub
//		
//		System.out.println("11");
//		System.out.println("12");
//		System.out.println("13");
//		System.out.println("14");
//		System.out.println("15");
//		System.out.println(100/0);
//		System.out.println("16");
//		System.out.println("17");
//		System.out.println("18");
//		System.out.println("19");
//
//	}
//
//}

//What are Errors?
//1 The error signifies a situation that mostly happens due to the absence of system resources. The system crash and memory errors are an example of errors. It majorly occurs at runtime.
// 2 recoverable
// 3   ye 2 type ki hoti h 1 compile time (checked exception) 2 run time (unchecked exception)

//What are Exceptions?
//The exceptions are the issues that can appear at runtime and compile time. It majorly arises in the code or program authored by the developers. There are two types of exceptions: Checked exceptions and Unchecked exceptions.
//2 non recoverable 
//3  1 type ki he hoti h run time (unchecked exception)

//Checked exceptions
//1 Checked exceptions occur at compile time.
//2 The compiler checks a checked exception.
//3 These types of exceptions can be handled at the time of compilation.
//4 Here, the JVM needs the exception to catch and handle.
//5 Examples of Checked exceptions:
//	File Not Found Exception
//	No Such Field Exception
//	Interrupted Exception
//	No Such Method Exception
//	Class Not Found Exception

//public class whatException {
//
//	public static void main(String[] args) {
//
//		FileInputStream f1 = new FileInputStream("d:/abc.text");
//	}
//}

//public class whatException {
//
//	public static void main(String[] args) {
//
//		try {
//			FileInputStream f1 = new FileInputStream("d:/abc.text");
//		} catch (FileNotFoundException e) {
//			// TODO Auto-generated catch block
//			e.printStackTrace();
//		}
//	}
//}

//Unchecked Exception
//1 Unchecked exceptions occur at runtime.
//2 The compiler does not check these types of exceptions.
//3 These types of exceptions cannot be a catch or handle at the time of compilation, because they get generated by the mistakes in the program
//4 Here, the JVM does not require the exception to catch and handle
//5 Examples of Unchecked Exceptions:
//	No Such Element Exception
//	Undeclared Throwable Exception
//	Empty Stack Exception
//	Arithmetic Exception
//	Null Pointer Exception
//	Array Index Out of Bounds Exception
//	Security Exception

//public class whatException {
//
//	public static void main(String[] args) {
//		// TODO Auto-generated method stub
//
//		System.out.println(100 / 0);
//	}
//}